### ISSUE TITLE
Wasm build but does not run

### ISSUE THREAD

**Issue by blobinabottle** [fabioarnold/nanovg-zig#7]
Hi

I'm trying to run the wasm version (`zig build -Dtarget=wasm32-freestanding`) the build seems ok as no error returned.

But when I run the index.html (live server on vcode) it complains no finding instance.exports.onInit();
From what I see it has built a very simple wasm file with only "memory" into the exports. 

I'm doing this on Mac (M1), maybe this is the issue? Am I missing something super obvious?

Thanks!

**Comment by fabioarnold** [comment]
Thanks for reporting this issue! Could you please try again and confirm it's fixed?

**Comment by blobinabottle** [comment]
You're so fast you broke Github :-) It is fixed, thank you!
